#!/bin/bash

python ZSMarketData_v0.1.py AMEX
echo "AMEX Data Loaded"
python ZSMarketData_v0.1.py NYSE
echo "NYSE Data Loaded"
python ZSMarketData_v0.1.py NASDAQ
echo "NASDAQ Data Loaded"

python ZSMarketScan_v0.1.py AMEX 01/01/2013 01/31/2014 SPY &
echo "AMEX Scan Completed"
python ZSMarketScan_v0.1.py NYSE 01/01/2013 01/31/2014 SPY &
echo "NYSE Scan Completed"
python ZSMarketScan_v0.1.py NASDAQ 01/01/2013 01/31/2014 SPY &
echo "NASDAQ Scan Completed"


